version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    command: --check-caps false --ISCAgent false
    ports: 
      - 51443:1972
      - 52443:52773
      - 53773
    volumes:
    #  - ~/iris.key:/usr/irissys/mgr/iris.key
      - ./:/irisdev/app